### ISSUE TITLE
when i install UItweaks 4.0.0 in BS 1.37.1, it make my game freeze

### ISSUE THREAD

**Issue by RuoChennn** [Exomanz/UITweaks#12]

**Comment by RuoChennn** [comment]
detail in log 
[2024.08.08.00.48.25.log](https://github.com/user-attachments/files/16531905/2024.08.08.00.48.25.log)

**Comment by RuoChennn** [comment]
and config file
[UITweaks.json](https://github.com/user-attachments/files/16531925/UITweaks.json)

**Comment by Exomanz** [comment]
Hello!

Thank you for submitting this issue. This is a known bug and is currently being worked on. The current workaround is to enable "Advanced HUD" inside of the player settings page.

UITweaks v4.0.1 will fix this issue and I will link it back here upon release.

**Comment by Exomanz** [comment]
[UITweaks v4.0.1](../releases/tag/v4.0.1) has fixed this issue. 👍
