### ISSUE TITLE
The links in the preview section are dead

### ISSUE THREAD

**Issue by ThePinkUnicorn6** [Exomanz/UITweaks#4]
The standard gameplay link and online gameplay link in the previews section of the readme both take you to a 404 page instead of wherever it is suposed to go.

**Comment by Exomanz** [comment]
Hi there! Thanks for the report. Looks like I just accidentally deleted them when I merged branches.

They should both be back and working now. :)

**Comment by ThePinkUnicorn6** [comment]
Yep they do, thanks!
