### ISSUE TITLE
Progress bar doesn't show

### ISSUE THREAD

**Issue by thebrightspark** [Exomanz/UITweaks#5]
Just used this mod for the first time today, using Beat Saber v1.18.2 and UITweaks v2.0.0.
However the progress bar didn't show up for me while playing maps, even though it was enabled in the mod settings.

**Comment by Exomanz** [comment]
Hey there! Thanks for the report. 
Can you verify that "Advanced HUD" is enabled under the "Player Options" tab in the song selection menu?

**Comment by thebrightspark** [comment]
Sorry for taking a while, couldn't find the time to jump back into BS until now.

Yes, I had that setting disabled! I didn't know about that setting before. It's all good and works now, thanks!
