### ISSUE TITLE
Update for BeatSaber 1.19.0

### ISSUE THREAD

**Issue by carlbennett** [Exomanz/UITweaks#7]
As the title suggests, please rebuild this mod for 1.19.0 and upload to BeatMods.com. All required dependencies (BSIPA, BeatSaberMarkupLanguage, SiraUtil) have been updated for 1.19.0. Thanks in advance!

**Comment by Exomanz** [comment]
Hi there.

Unfortunately with SiraUtil v3 becoming available, I took the opportunity to rewrite the mod and improve it which made this take a lot longer than it should've. 

A build for 1.19.0 is now available.
