### ISSUE TITLE
The UI is reversed，is that a joke？

### ISSUE THREAD

**Issue by hotcpu1949** [Exomanz/UITweaks#8]
RT

**Comment by hotcpu1949** [comment]
In BeatSaber 1.20/1.21，UITweaks3.0.6

**Comment by Exomanz** [comment]
This is intentional behavior due to the fact that it is April 1st. 

It can be disabled by editing `UITweaks.json` in your Beat Saber/UserData folder and setting AprilFools to false. You can do this by using Notepad or any text editor.

**Comment by hotcpu1949** [comment]
Thanks & that's a great ,very useful pluguin :)


| |
hotcpu
|
|
***@***.***
|
On 4/2/2022 ***@***.***> wrote：

This is intentional behavior due to the fact that it is April 1st.

It can be disabled by editing UITweaks.json in your Beat Saber/UserData folder and setting AprilFools to false. You can do this by using Notepad or any text editor.
